lang: en
project:
  type: website
  output-dir: _site
  resources:
    - resolved-repos.json
  render:
    - index.qmd
    - example.qmd
    - examples.qmd
website:
  title: CTM Assessment
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: example.qmd
        text: Working examples
format:
  html:
    toc: true
    theme: cosmo
filters:
  - ctm-assessment
ai-feedback:
  policy-files: feedback.yml
  mode: copy
  storage: local
py-exercise:
  feedback: true
  show-test-hints: true
  submission: false

pyodide:
  feedback: true
  feedback-hints: true
